"""
Step 2: Transform (dbt)
=======================
This script acts as a Python wrapper to execute `dbt run` for the analytical models.
It compiles the raw relational tables generated by `dlt` into beautiful, flat analytics views suitable for Metabase.

Usage:
    python3 2_transform.py [options]

Options:
    --target           Target database profile for dbt (dev_duckdb or dev_sqlite, default: dev_duckdb)
    --db_path          Explicit path to the database file (overrides profiles.yml via environment variable)
    --dbt_project_dir  Path to the dbt project directory (default: analytics_transform)
"""
import subprocess
import sys
import os
import argparse

parser = argparse.ArgumentParser(description="Transform loaded data using dbt")
parser.add_argument("--target", type=str, default="dev_duckdb", choices=["dev_duckdb", "dev_sqlite"], help="Target database profile for dbt")
parser.add_argument("--db_path", type=str, default=None, help="Path to the database file")
parser.add_argument("--dbt_project_dir", type=str, default="analytics_transform", help="Path to the dbt project directory")
args = parser.parse_args()

# 1. Configuration
TARGET = args.target

def run_dbt():
    print(f"Starting dbt transformations (Target: {TARGET})...")
    
    # Path to the dbt project folder
    dbt_project_dir = os.path.abspath(args.dbt_project_dir)
    
    # Set the environment variable for DBT if db_path is provided
    env = os.environ.copy()
    if args.db_path:
        env["DBT_DB_PATH"] = os.path.abspath(args.db_path)
    
    # Execute the dbt run command
    result = subprocess.run(
        ["dbt", "run", "--profiles-dir", ".", "--target", TARGET],
        cwd=dbt_project_dir,
        env=env,
        capture_output=True,
        text=True
    )
    
    # Output the results
    if result.returncode == 0:
        print("Success! All dbt models ran successfully.")
        print("--------------------------------------------------")
        print(result.stdout)
    else:
        print("Error: dbt run failed!")
        print("--------------------------------------------------")
        print(result.stdout)
        print(result.stderr)
        sys.exit(1)

if __name__ == "__main__":
    run_dbt()
